# Generated by Django 4.2.2 on 2023-06-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('avatar', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('get_notification', models.CharField(max_length=50)),
                ('answer_count', models.PositiveIntegerField(default=0)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('point', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
